name=Caza20 - AW20216S
version=0.1.0
author=Matias Cazanave (https://matiascazanave.my.canva.site/)
maintainer=Matias Cazanave (https://matiascazanave.my.canva.site/)
sentence=AW20216B SPI LED Driver library
paragraph=Provides a simple SPI-based API to control the AW20216S RGB LED matrix driver, including per-LED color and brightness, PWM frequency configuration and several ready-to-run examples.
sentence=AW20216B SPI LED Driver library
paragraph=Provides a simple SPI-based API to control the AW20216S RGB LED matrix driver, including per-LED color and brightness, PWM frequency configuration and several ready-to-run examples.
category=Communication
url=
architectures=*
includes=AW20216S.h